substitutions:
  _BUCKET: 'tf_bigquery_scripts_bucket'
  _PROJECT_ID: 'trusted-zone-466913' # ALTERE DE ACORDO COM O PROJETO DE DESTINO
  _LAYER: 'trusted'                  # ALTERE DE ACORDO COM A CAMADA DE DESTINO
  _TABLE: 'tb_sample_sales'          # ALTERE DE ACORDO COM A TABELA DE DESTINO

logsBucket: 'cloudbuild-logs-data-gbq-466417'
timeout: 3600s

steps:

  # 0. Sincroniza todos os artefatos (substitui os existentes)
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🔄 Sincronizando Artefatos (substituindo os existentes)..."
        gsutil -m rsync -d -r data-gbq gs://$_BUCKET/

  # 1. Executa o DDL da Tabela no BigQuery
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Executando DDL da Tabela $_TABLE na camada $_LAYER..."
        DDL_FILE="gs://$_BUCKET/$_LAYER/$_TABLE/ddl_${_TABLE}.sql"
        if gsutil -q stat ${DDL_FILE}; then
          echo "Arquivo encontrado: ${DDL_FILE}"
          bq query --project_id=${_PROJECT_ID} --use_legacy_sql=false "$(gsutil cat ${DDL_FILE})"
          echo "✅ DDL executado com sucesso."
        else
          echo "⚠️ Nenhum DDL encontrado para ${_TABLE}, pulando step..."
        fi

  # 2. Executa a Procedure de Carga da Tabela no BigQuery
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Criando/Atualizando Procedure de carga da Tabela $_TABLE na camada $_LAYER..."
        PROC_FILE="gs://$_BUCKET/$_LAYER/$_TABLE/prc_load_${_TABLE}.sql"
        if gsutil -q stat ${PROC_FILE}; then
          echo "Arquivo encontrado: ${PROC_FILE}"
          bq query --project_id=${_PROJECT_ID} --use_legacy_sql=false "$(gsutil cat ${PROC_FILE})"
          echo "✅ Procedure criada/atualizada com sucesso."
        else
          echo "⚠️ Nenhuma procedure encontrada para ${_TABLE}, pulando step..."
        fi
